spring.application.name=app_proxy_service
server.port=7070
app.keycloak-url=http://192.168.25.17:8080
app.frontend-url=http://192.168.25.17:4200
app.backend-uri=http://192.168.25.17:9191
spring.security.oauth2.client.registration.keycloak.client-id=rbs-backend
spring.security.oauth2.client.registration.keycloak.client-secret=981BeO77JzBeR58jeObiIkMScHIrl5wz
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.keycloak.issuer-uri=${app.keycloak-url}/realms/apprpsa
spring.security.oauth2.resourceserver.jwt.issuer-uri=${app.keycloak-url}/realms/apprpsa
spring.cloud.gateway.server.webflux.routes[0].id=back-srpsa-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://${app.backend-uri}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=TokenRelay=


